import { PenLine, RefreshCw, Image, Globe, Link2, ClipboardCopy, Heart } from 'lucide-react'

const FEATURES = [
    { icon: <PenLine className="w-7 h-7" />, title: 'AI Content Writing', desc: 'Generate SEO-optimized articles from scratch with focus keywords and LSI integration.' },
    { icon: <RefreshCw className="w-7 h-7" />, title: 'Post Rewriting', desc: 'Paste any blog post URL and rewrite it with better SEO, keywords, and structure.' },
    { icon: <Image className="w-7 h-7" />, title: 'Image Prompts', desc: 'Get AI-generated image prompts mapped to each section of your content.' },
    { icon: <Globe className="w-7 h-7" />, title: 'Multi-Language', desc: 'Write content in English, Spanish, French, German, Italian, Portuguese and more.' },
    { icon: <Link2 className="w-7 h-7" />, title: 'Internal Linking', desc: 'Provide your sitemap and let AI weave in relevant internal links automatically.' },
    { icon: <ClipboardCopy className="w-7 h-7" />, title: 'WordPress Ready', desc: 'Copy formatted content directly to WordPress, or download as .txt or .md files.' },
]

const STEPS = [
    { num: '01', title: 'Enter Keywords', desc: 'Provide your focus keyword, LSI keywords, and target audience — or paste a URL to rewrite.' },
    { num: '02', title: 'AI Generates Content', desc: 'Gemini AI crafts SEO-optimized content with proper headings, structure, and keyword integration.' },
    { num: '03', title: 'Export & Publish', desc: 'Copy to clipboard, download as markdown, or edit inline — then publish to your site.' },
]

const FAQS = [
    { q: 'Is this tool really free?', a: 'Yes! Wm AI Writer is completely free and open-source. Since you provide your own Google Gemini API key, there are no subscription fees or usage limits imposed by us.' },
    { q: 'Where is my data stored?', a: 'Nowhere. This is a 100% client-side application running entirely in your browser. We do not have servers, databases, or accounts. Your API key and content never leave your device.' },
    { q: 'Can I use this for commercial websites?', a: 'Absolutely. The content generated by Gemini is yours to use however you see fit, including on monetized blogs, client sites, and e-commerce stores.' },
    { q: 'What is the "Rewrite Post" feature?', a: 'It allows you to paste the URL of an existing, underperforming blog post. The AI will extract the content and completely rewrite it targeting new keywords, improving its formatting and SEO value.' }
]

export default function HomeSections() {
    return (
        <div className="max-w-6xl mx-auto space-y-24 pb-20">

            {/* What Is This Tool */}
            <section className="text-center max-w-3xl mx-auto">
                <h2 className="text-3xl sm:text-4xl font-bold text-earth-dark dark:text-light-cream mb-4">
                    What is <span className="text-forest dark:text-forest-light">Wm AI Writer</span>?
                </h2>
                <p className="text-base sm:text-lg text-earth-dark/60 dark:text-light-cream/60 leading-relaxed">
                    Wm AI Writer is a free, browser-based SEO content tool powered by Google Gemini AI.
                    Write new articles or rewrite existing posts — all optimized for search engines.
                    Your API key stays in your browser. No accounts, no servers, no data stored.
                </p>
            </section>

            {/* How It Works */}
            <section id="how-it-works" className="scroll-mt-32">
                <h2 className="text-3xl sm:text-4xl font-bold text-center text-earth-dark dark:text-light-cream mb-12">
                    How It Works
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {STEPS.map((s) => (
                        <div key={s.num} className="card text-center group hover:shadow-xl hover:shadow-forest/10 dark:hover:shadow-forest-light/5 transition-all duration-300">
                            <div className="inline-flex items-center justify-center w-14 h-14 rounded-2xl bg-forest/10 dark:bg-forest-light/10 text-forest dark:text-forest-light text-xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                                {s.num}
                            </div>
                            <h3 className="text-lg font-semibold text-earth-dark dark:text-light-cream mb-2">{s.title}</h3>
                            <p className="text-sm text-earth-dark/50 dark:text-light-cream/50 leading-relaxed">{s.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Features */}
            <section id="features" className="scroll-mt-32">
                <h2 className="text-3xl sm:text-4xl font-bold text-center text-earth-dark dark:text-light-cream mb-12">
                    Features
                </h2>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                    {FEATURES.map((f) => (
                        <div key={f.title} className="card group hover:shadow-xl hover:shadow-forest/10 dark:hover:shadow-forest-light/5 transition-all duration-300">
                            <div className="w-12 h-12 rounded-xl bg-forest/10 dark:bg-forest-light/10 text-forest dark:text-forest-light flex items-center justify-center mb-3 group-hover:scale-110 transition-transform duration-300">{f.icon}</div>
                            <h3 className="text-base font-semibold text-earth-dark dark:text-light-cream mb-1.5">{f.title}</h3>
                            <p className="text-sm text-earth-dark/50 dark:text-light-cream/50 leading-relaxed">{f.desc}</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* FAQ Section */}
            <section id="faq" className="scroll-mt-32 max-w-4xl mx-auto">
                <h2 className="text-3xl sm:text-4xl font-bold text-center text-earth-dark dark:text-light-cream mb-12">
                    Frequently Asked Questions
                </h2>
                <div className="space-y-4">
                    {FAQS.map((faq, idx) => (
                        <div key={idx} className="card p-6 border border-forest/10 dark:border-forest-light/10 hover:border-forest/30 dark:hover:border-forest-light/30 transition-colors">
                            <h3 className="text-lg font-semibold text-earth-dark dark:text-light-cream mb-2 flex gap-3">
                                <span className="text-forest dark:text-forest-light">Q.</span> {faq.q}
                            </h3>
                            <p className="text-sm text-earth-dark/70 dark:text-light-cream/70 leading-relaxed pl-7">
                                {faq.a}
                            </p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Footer */}
            <footer className="text-center pt-12 pb-8 border-t border-earth-dark/10 dark:border-light-cream/10">
                <p className="text-sm text-earth-dark/60 dark:text-light-cream/60 mb-2 flex items-center justify-center gap-1.5">
                    Wm AI Writer — Built with <Heart className="w-4 h-4 text-red-500 fill-red-500" /> using Google Gemini AI
                </p>
                <p className="text-sm font-medium text-earth-dark dark:text-light-cream">
                    Developed by <a href="https://www.facebook.com/prowebfixer" target="_blank" rel="noopener noreferrer" className="text-forest dark:text-forest-light hover:underline font-bold">Rashedul</a>
                </p>
                <p className="text-xs text-earth-dark/40 dark:text-light-cream/40 mt-4">
                    Your API key never leaves your browser. 100% client-side privacy.
                </p>
            </footer>
        </div>
    )
}
