// Common AI-generated phrases and words to avoid for human-sounding content
// Sources: frequency analysis of AI vs human writing patterns

export const AI_PHRASES_TO_AVOID = [
    'provide a valuable insight',
    'left an indelible mark',
    'a stark reminder',
    'a nuanced understanding',
    'significant role in shaping',
    'the complex interplay',
    'broad implication',
    'an unwavering commitment',
    'endure a legacy',
    'underscore the importance',
    'play a pivotal role',
    'a pivotal moment',
    'navigate the complex',
    'mark a turning point',
    'continue to inspire',
    'gain a deeper understanding',
    'the transformative power',
    'hold a significant',
    'play a crucial role',
    'particularly a concern',
    'the relentless pursuit',
    'emphasize the need',
    'target an intervention',
    'a multi-faceted approach',
    'highlight the potential',
    'a significant milestone',
    'potential risk associated',
    'leave a lasting',
    'add a layer',
    'offer a valuable',
    'a profound implication',
    'case highlights the importance',
    'pave the way for the future',
    'a significant step forward',
    'face a significant',
    'emphasize the importance',
    'a significant implication',
    'delve deeper into',
    'raise an important question',
    'make an informed decision',
    'far-reaching implications',
    'a comprehensive framework',
    'a unique blend',
    "couldn't help but wonder",
    'underscore the need',
    'framework for understanding',
    'highlight the need',
    'a comprehensive understanding',
    'the journey begins',
    'understanding the fundamental',
    'a delicate balance',
    'the path ahead',
    'gain an insight',
    'laid the groundwork',
    'renew a sense',
    'aim to explore',
    'present a unique challenge',
    'provide a comprehensive',
    'address the root cause',
    'loom large in',
    'an ongoing dialogue',
    'carry a weight',
    'ability to navigate',
    'present a significant',
    'shed light on',
    'a diverse perspective',
    'face an adversity',
    'a comprehensive overview',
    'potentially lead to',
    'a broad understanding',
    'contribute to the understanding',
    'shape the public',
    'particularly noteworthy',
    'identify an area of improvement',
    'undergone a significant',
    'initiative aims to',
    'offering a unique',
    'a new avenue',
    'despite the challenge',
    'ready to embrace',
    'the societal expectation',
    'today at a fast pace',
    'stand in stark contrast',
    'in today\'s fast-paced world',
    'it\'s important to note',
    'it\'s worth noting',
    'in conclusion',
    'in the realm of',
    'game-changer',
    'take it to the next level',
    'think outside the box',
    'at the end of the day',
]

export const AI_WORDS_TO_AVOID = [
    'delve',
    'harnessing',
    'facilitating',
    'intrinsic',
    'integral',
    'facet',
    'nuance',
    'culmination',
    'manifestation',
    'inherent',
    'confluence',
    'intricacies',
    'epitomize',
    'embodiment',
    'synthesize',
    'amplify',
    'impetus',
    'catalyst',
    'synergy',
    'cohesive',
    'paradigm',
    'prerequisite',
    'holistic',
    'quintessential',
    'cohesion',
    'symbiosis',
    'encompass',
    'unveil',
    'unravel',
    'emanate',
    'illuminate',
    'reverberate',
    'augment',
    'infuse',
    'extrapolate',
    'embody',
    'unify',
    'inflection',
    'instigate',
    'embark',
    'envisage',
    'elucidate',
    'substantiate',
    'resonate',
    'catalyze',
    'evoke',
    'pinnacle',
    'tapestry',
    'leverage',
    'centerpiece',
    'subtlety',
    'immanent',
    'exemplify',
    'archetypal',
    'conceptualize',
    'reinforce',
    'mosaic',
]

/** Build a compact prompt section listing phrases and words to avoid */
export function buildAvoidancePrompt(): string {
    const phrasesBlock = AI_PHRASES_TO_AVOID.map(p => `- "${p}"`).join('\n')
    const wordsBlock = AI_WORDS_TO_AVOID.join(', ')

    return `
CRITICAL — Write like a real human, NOT like AI. Avoid these overused AI phrases and words entirely:

Phrases to NEVER use:
${phrasesBlock}

Words to NEVER use: ${wordsBlock}

Instead:
- Use simple, direct language a human blogger would naturally write
- Vary sentence length — mix short punchy sentences with longer ones
- Use contractions (don't, isn't, we're, you'll)
- Include casual transitions (but, so, now, here's the thing, look)
- Write like you're explaining to a friend, not giving a lecture
- Avoid starting paragraphs with "In today's..." or "It's important to note..."
- Don't use filler phrases that don't add meaning`
}
